version: '3.1'
services:

  field-weather-management:
    build: .
    container_name: field-weather-management
    ports:
      - "18080:8080"
      - "18787:8787"
    restart: always
    depends_on:
      - postgresdb

  postgresdb:
    image: postgres
    container_name: postgresdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - PGDATA=/data/postgres
    volumes:
      - ~/data/postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  prometheus_data: {}
  grafana_data: {}
  esdata1:
    driver: local